# Generated by Django 4.2.4 on 2023-09-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_alter_transaction_book_alter_transaction_issue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.book'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libapp.member'),
        ),
    ]
