# Generated by Django 4.2.4 on 2023-09-01 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0004_alter_transaction_book_alter_transaction_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issue_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 9, 1, 10, 58, 13, 485031, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
